### ISSUE TITLE
Chambers of Xeric reload problem

### ISSUE THREAD

**Issue by Jisukekw** [JacobLindelof/runelite-plugins#6]
Chambers Of Xeric default runelite plugin does not automaticly refresh the layout when you do a reload at the raid entrance stairs if you have "Low Detail Chambers" plugin on. Even "CoX Scouter External" won't work if the low detail is on.

**Comment by bepzi** [comment]
Related to https://github.com/bepzi/runelite-plugins/issues/2

@JacobLindelof Please see https://github.com/JacobLindelof/runelite-plugins/pull/5 for a ready-to-merge fix

**Comment by JacobLindelof** [comment]
thx for the PR sorry ive been MIA. haven't been playing much OSRS.
